# Add 'label1' to any changes within 'examples' folder or any subfolders
area/docs:
  - docs/**/*
  - ./*.md

area/housekeeping:
  - .github/**/*
  - ./.gitignore

area/cicd:
  - .github/workflows/**/*

type/manifest:
  - ./**/manifest.yml

type/dockerfile:
  - ./**/Dockerfile

type/python:
  - ./**/*.py

type/readme:
  - ./**/README

type/config:
  - ./**/config.yml

tests:
  - ./**/tests/*

component/executor:
  - executors/**/*

component/encoder:
  - encoders/**/*

component/indexer:
  - indexers/**/*

component/ranker:
  - rankers/**/*

component/crafter:
  - crafters/**/*