name: CD

#on:
#  pull_request:
#    branches:
#      - master
#    types: [ closed ]


on:
  push:
    branches-ignore:
      - '**'  # temporally ignore all


jobs:
  hub-build-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jina Hub Image Builder
        uses: jina-ai/hub-builder@master