name: CD

on:
  pull_request:
    branches:
      - master
    types: [ closed ]


#on:
#  push:
#    branches-ignore:
#      - '**'  # temporally ignore all


jobs:
  hub-build-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jina Hub Login
        run: |
          mkdir -p ${ACCESS_DIRECTORY}
          if [ ! -f ${ACCESS_FILE} ]; then touch ${ACCESS_FILE}; echo "access_token: ${GITHUB_TOKEN}" >> ${ACCESS_FILE}; fi
        env:
          ACCESS_DIRECTORY: ~/.jina
          ACCESS_FILE: ~/.jina/access.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Jina Hub Image Builder
        uses: jina-ai/hub-builder@master
        with:
          push: true
          dockerhub_username: ${{ secrets.JINAHUB_DOCKER_USER }}
          dockerhub_password: ${{ secrets.JINAHUB_DOCKER_PWD }}
          slack_webhook: ${{ secrets.JINAHUB_SLACK_WEBHOOK }}
